npmRegistryServer: 'https://artifactory.aws.athenahealth.com:443/api/npm/npm'

npmScopes:
  athena:
    npmPublishRegistry: 'https://artifactory.aws.athenahealth.com:443/api/npm/npm-local'
    npmRegistryServer: 'https://artifactory.aws.athenahealth.com:443/api/npm/npm-local'

packageExtensions:
  '@scope/nimbus-core@0.9.20':
    dependencies:
      yargs: ^17.5.1
  '@storybook/theming@6.4.22':
    dependencies:
      '@emotion/serialize': ^1.0.3
      '@emotion/utils': ^1.1.0
  '@svgr/cli@6.2.1':
    dependencies:
      prettier: ^2.6.2
  '@types/babel__standalone@7.1.4':
    dependencies:
      '@types/babel__core': ^7.1.14
  chalk@5.0.1:
    dependencies:
      '#ansi-styles': npm:ansi-styles@6.1.0
      '#supports-color': npm:supports-color@9.2.2
  eslint-config-react-app@7.0.1:
    peerDependencies:
      '@typescript-eslint/eslint-plugin': ^5.20.0
  gatsby-plugin-amplitude-analytics@3.2.0:
    dependencies:
      minimatch: ^5.0.1
  gatsby@4.14.1:
    dependencies:
      '@reach/router': ^1.3.4
      '@types/reach__router': ^1.3.10
    peerDependencies:
      '@types/react-dom': ^17.0.2
  html-react-parser@1.4.11:
    dependencies:
      htmlparser2: 7.2.0
  mdast-util-gfm-table@1.0.4:
    dependencies:
      '@types/mdast': ^3.0.0
  react-markdown@7.1.2:
    dependencies:
      '@types/prop-types': ^15.7.5
  react-overlays@5.1.1:
    peerDependencies:
      '@types/prop-types': ^15.7.5
  react-storybook-addon-props-combinations@1.1.0:
    dependencies:
      babel-runtime: ^6.26.0
  reactabular-table@8.14.0:
    dependencies:
      'prop-types': ^15.8.1
      'lodash': ^4.17.21

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

pnpEnableEsmLoader: true

unsafeHttpWhitelist:
  - '*.artifactory.aws.athenahealth.com'
  - artifactory.aws.athenahealth.com

yarnPath: .yarn/releases/yarn-3.2.2.cjs
